apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-backend
  template:
    metadata:
      labels:
        app: login-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done']
      containers:
        - name: login-backend
          image: login-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/logindb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: hasini@1416
---
apiVersion: v1
kind: Service
metadata:
  name: login-backend
spec:
  selector:
    app: login-backend
  ports:
    - port: 8080
      targetPort: 8080